# Generated by Django 4.2 on 2023-07-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_chat_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="describe_issues",
            field=models.TextField(default=None, max_length=3000),
        ),
    ]
