# Generated by Django 4.2 on 2023-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_category_alter_tracker_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="issue",
            field=models.CharField(
                choices=[
                    ("engine", "engines"),
                    ("lights", "lights"),
                    ("door", "door"),
                    ("fluid", "fluid"),
                ],
                default=None,
                max_length=30,
            ),
        ),
    ]
