# Generated by Django 4.2 on 2023-07-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_alter_tracker_issue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("model", models.CharField(max_length=300)),
                ("year", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="tracker",
            name="car_name",
            field=models.ForeignKey(
                max_length=300,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.car",
            ),
        ),
    ]
